export type Process = { title: string; steps: string[] };

export const processes: Process[] = [
  { title: "User Access Provisioning", steps: ["Access Request", "Manager Approval", "IAM Validation", "Account Provisioning", "Access Confirmation"] },
  { title: "Access Recertification", steps: ["Identify Users", "Review Access", "Manager Certification", "Remove Excess Access", "Close Review"] },
  { title: "Multi Factor Authentication Setup", steps: ["User Enrollment", "Register Device", "Configure MFA", "Verification", "Activation"] },
  { title: "Break Glass Account Usage", steps: ["Emergency Identified", "Access Approval", "Break Glass Login", "Activity Monitoring", "Access Revocation"] },
  { title: "Privileged Access Management", steps: ["Access Request", "Risk Review", "PAM Approval", "Grant Privileged Access", "Session Monitoring"] },
  { title: "Role Based Access Control", steps: ["Define Role", "Map Permissions", "Assign User", "Validate Access", "Review Access"] },
  { title: "Access Revocation", steps: ["Termination Request", "Review Access", "Disable Accounts", "Remove Privileges", "Close Request"] },
  { title: "Single Sign-On Implementation", steps: ["Application Registration", "Identity Integration", "Configure SSO", "User Testing", "Go Live"] },
  { title: "Identity Federation", steps: ["Partner Agreement", "Trust Configuration", "Identity Mapping", "Authentication Testing", "Activation"] },
  { title: "Conditional Access Policy", steps: ["Define Rules", "Create Policy", "Assign Users", "Test Access", "Enable Policy"] },
  { title: "Security Incident Handling", steps: ["Alert Generated", "Incident Triage", "Contain Threat", "Remediate Issue", "Close Incident"] },
  { title: "Major Incident Process", steps: ["Incident Logged", "Declare Major Incident", "War Room Creation", "Service Restoration", "Post Incident Review"] },
  { title: "Root Cause Analysis", steps: ["Problem Identified", "Evidence Collection", "Cause Analysis", "Corrective Action", "Review Findings"] },
  { title: "Incident Escalation", steps: ["Incident Assignment", "Investigation", "Escalation Decision", "Higher Support Engagement", "Resolution"] },
  { title: "Digital Forensics Investigation", steps: ["Incident Detection", "Evidence Collection", "Evidence Preservation", "Forensic Analysis", "Report Findings"] },
  { title: "Threat Containment Process", steps: ["Threat Identification", "System Isolation", "Block Malicious Activity", "Monitor Environment", "Restore Services"] },
  { title: "Evidence Preservation", steps: ["Identify Evidence", "Capture Evidence", "Secure Storage", "Maintain Chain Of Custody", "Review Evidence"] },
  { title: "Security Monitoring Workflow", steps: ["Collect Logs", "Analyze Events", "Generate Alerts", "Investigate Activity", "Close Event"] },
  { title: "Alert Triage Process", steps: ["Receive Alert", "Validate Alert", "Assess Severity", "Assign Analyst", "Begin Investigation"] },
  { title: "Post Incident Review", steps: ["Gather Data", "Review Timeline", "Identify Lessons Learned", "Define Improvements", "Share Findings"] },
  { title: "Vulnerability Management", steps: ["Identify Vulnerability", "Assess Risk", "Prioritize Findings", "Apply Fix", "Verify Remediation"] },
  { title: "Penetration Testing Lifecycle", steps: ["Planning", "Reconnaissance", "Testing", "Report Findings", "Remediation"] },
  { title: "Data Classification", steps: ["Identify Data", "Assess Sensitivity", "Assign Classification", "Apply Controls", "Review Classification"] },
  { title: "DLP Incident Handling", steps: ["Policy Triggered", "Alert Generated", "Investigate Event", "Contain Exposure", "Close Incident"] },
  { title: "Encryption Key Management", steps: ["Generate Key", "Store Key", "Distribute Key", "Rotate Key", "Retire Key"] },
  { title: "Security Awareness Campaign", steps: ["Create Content", "Schedule Training", "Deliver Training", "Assess Users", "Publish Results"] },
  { title: "Phishing Simulation", steps: ["Design Campaign", "Launch Simulation", "Track Responses", "Identify Risks", "Provide Training"] },
  { title: "Patch Management Process", steps: ["Identify Patch", "Test Patch", "Approve Deployment", "Deploy Patch", "Validate Systems"] },
  { title: "Threat Intelligence Lifecycle", steps: ["Collect Intelligence", "Analyze Threats", "Assess Impact", "Distribute Insights", "Update Controls"] },
  { title: "Compliance Audit", steps: ["Audit Planning", "Evidence Collection", "Control Testing", "Identify Gaps", "Publish Report"] },
  { title: "Firewall Rule Change", steps: ["Request Change", "Review Requirement", "Implement Rule", "Test Connectivity", "Close Change"] },
  { title: "VPN Access Setup", steps: ["Access Request", "Approval", "VPN Configuration", "Credential Setup", "Connectivity Test"] },
  { title: "Network Segmentation", steps: ["Identify Assets", "Define Zones", "Configure Policies", "Implement Segmentation", "Validate Traffic"] },
  { title: "IP Whitelisting Process", steps: ["Request Access", "Validate IP", "Approve Request", "Update Firewall", "Verify Access"] },
  { title: "Intrusion Detection Workflow", steps: ["Monitor Traffic", "Detect Event", "Generate Alert", "Investigate Activity", "Close Event"] },
  { title: "Secure SDLC", steps: ["Requirements Review", "Secure Design", "Secure Development", "Security Testing", "Deployment"] },
  { title: "Static Security Testing", steps: ["Source Code Scan", "Identify Issues", "Review Findings", "Fix Defects", "Rescan Application"] },
  { title: "Dynamic Security Testing", steps: ["Deploy Application", "Run DAST Scan", "Analyze Results", "Fix Vulnerabilities", "Validate Fixes"] },
  { title: "Container Security", steps: ["Build Image", "Scan Image", "Fix Vulnerabilities", "Deploy Container", "Monitor Runtime"] },
  { title: "Supply Chain Security", steps: ["Identify Dependencies", "Assess Risks", "Validate Sources", "Apply Controls", "Continuous Monitoring"] },
];

export const teams = ["A", "B", "C", "D", "E", "F"] as const;
export type Team = (typeof teams)[number];
